version: '2'

services:
   fabric_ca:
      container_name: fabric-ca
      image: hyperledger/fabric-ca:latest
      volumes:
         - "./hlf-enerji/:/hlf-enerji"
      command:
         - /hlf-enerji/gen-fabric-ca-docker.sh
      tty: true
   orderer-peer:
      container_name: orderer-peer
      image: hyperledger/fabric-orderer:latest
      volumes:
         - "./hlf-enerji/:/hlf-enerji"
      command:
         - /hlf-enerji/start-orderer-docker.sh
      tty: true
      